# Site settings
title: You Only Live Once, So Treat Yo'self TODAY!!!
email: yolosty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <p>When you are feeling depressed, excited, happy, or sad...TREAT YO'SELF.</p>
  <p>Clothes --> TREAT YO'SELF</p>
  <p>Fragrances --> TREAT YO'SELF</p>
  <p>Massages --> TREAT YO'SELF</p>
  <p>Mimosas --> TREAT YO'SELF</p>
  <p>Fine Leather Goods --> TREAT YO'SELF</p>
  <p>&#9835; TODAY is the best day of the year! &#9835;</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yolosty.today" # the base hostname & protocol for your site
twitter_username: yolosty

# Build settings
markdown: kramdown
